{{- if .Values.rbac.create -}}
{{- if .Values.rbac.clusterRole -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubegraf.fullname" . }}
  labels:
    {{- include "kubegraf.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubegraf.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubegraf.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}

