apiVersion: v2
name: kubegraf
description: Advanced Kubernetes Visualization and Management Dashboard
type: application
version: 1.6.0
appVersion: "1.6.0"
home: https://github.com/kubegraf/kubegraf
sources:
  - https://github.com/kubegraf/kubegraf
maintainers:
  - name: KubeGraf Contributors
keywords:
  - kubernetes
  - dashboard
  - visualization
  - monitoring
  - management
annotations:
  category: Monitoring

